name: template
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=2.16.2 <3.0.0'
dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  # Architecture
  flutter_modular: ^4.5.1+1
  provider: ^6.0.2
  # State management
  mobx: ^2.0.7
  flutter_mobx: ^2.0.5
  # Remote API
  dio: ^4.0.6
  async: ^2.8.2
  # Data persistence
  hive: ^2.1.0
  # Error Handling
  dartz: ^0.10.1
  # Responsivity
  flutter_screenutil: ^5.4.0+1

dev_dependencies:
  flutter_test:
    sdk: flutter
  # Test tools
  mocktail: ^0.3.0
  faker: ^2.0.0
  modular_test: ^1.0.1+2
  # Code generators
  modular_codegen: ^3.0.4
  mobx_codegen: ^2.0.4
  build_runner: ^2.1.8

  flutter_lints: ^1.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/lang/
